
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible"content="IE=edge">
    <meta name="viewport"content="width=device-width,initial-scale=1.0">
    <title>Curriculum vitae</title>
</head>
<body>
    <!-- header -->
    <header>
	<table>
	     <tr>
	     	 <td>
		     <img src="https://scontent-hkg4-2.xx.fbcdn.net/v/t1.15752-9/370107172_1111866866464924_7276566183253429078_n.jpg?stp=dst-jpg_p1080x2048&_nc_cat=111&ccb=1-7&_nc_sid=8cd0a2&_nc_eui2=AeFSs9WI8v3G-O4ppEztf3Mjekqub7OQ6tx6Sq5vs5Dq3Cx3WmazqoN-LF218TMB9RtWsDlSBjAt6fn9cuB9hUat&_nc_ohc=4o4m0nCH3FAAX9BO-OK&_nc_ht=scontent-hkg4-2.xx&oh=03_AdR6fPiBuqGsFUk6zWPymYPIHDemta_im_mWY3EUvkax1Q&oe=657C297D" alt=""width="127px">
		 </td>
	         <tr>
		     <h1>Claryss Mae P. Pangasian</h1>
		 </td>
	     </tr>
	<table>
    </header>
    <br>
    <!-- Personal Details -->
    <section>
	<h2>Personal Details</h2>
	<hr>
	<table border="1px">
	    <tr>
		<td>
		    <h3>Name</h3>
		</td>
		<td>
		    <p>Claryss Mae P. Pangasian</p>
		</td>
	    </tr>
	    <tr>
		<td>
		    <h3>Email Address</h3>
		</td>
		<td>
		    <p>claryss.pangasian@neu.edu.ph</p>
		</td>
	    </tr>
	    <tr>
		<td>
		    <h3>Address</h3>
		</td>
		<td>
		    <p>Blk36-2 Iglesia Ni Cristo Tagumpay Housing, San jose, Rodriguez, Rizal</p>
		</td>
	    </tr>
	    <tr>
		<td>
		    <h3>Phone Number</h3>
		</td>
		<td>
		    <p>09497036580</p>
		</td>
	    </tr>
 	    <tr>
		<td>
		    <h3>Sex</h3>
		</td>
		<td>
		    <p>Female</p>
		</td>
	    </tr>
	</table>
    </section>
    <br>
    <!-- summary -->
    <section>
	<h2>Summary</h2>
	<hr>
	<p>I am a student who works hard, studies well, has a good academic record, and is ready to take on difficult tasks. Uses their schooling and personal skills to dig deeper into difficult topics and learn new things in detail. Ability to learn quickly and bring strong Microsoft Office skills.</p>
    </section>
    <br>
    <!-- education-->
    <section>
	<h2>Education</h2>
	<hr>
	<table>
	    <tr>
	    <td>
		<h3>Senior High School</h3>
	    <ul>
		<li>San jose Litex Senior High School: 2021 - 2023</li>
	    </ul>
	    </td>
 	    <td>
	   	<h3>Junior High School</h3>
	    <ul>
		<li>Tagumpay National High School: 2017 - 2021</li>
	    </ul>
	    </td>
	    <td>
	        <h3>Elementary School</h3>
	    <ul>
		<li>Tagumpay Elementary School: 2011 - 2017</li>
	    </ul>
	    </td>
	    </tr>
	</table>
    </section>
    <br>
    <!-- Skill -->
    <section>
	<h2>Skills</h2>
	<hr>
	<table cellspacing="20px">
	    <tr>
		<td>
		    <h3>Hard Skills</h3>
	            <ul>
	                <li>Programming Languages: Java</li>
	                <li>Integrated Development Environments (IDEs):Eclipse</li>
	                <li>Web Development:HTML</li>
	                 </ul>
		     </td>
		     <td>
	                 <h3>Soft Skills</h3>
	                 <ul>
	                     <li>Problem Solving:Proven ability to analyze and solve complex programming challenges.</li>
	                     <li>Teamwork:collaborated effectively in group projects, contributing to a positive team environment</li>
	                     <li>communication:Clearly communication technical concepts in both written and verbal forms.</li>
	                 </ul>
		     </td> 
	    </tr>
    </section>
    <br>
</body>
</html>
